### ISSUE TITLE
Standardize needs to check that data are available over the reference period

### ISSUE THREAD

**Issue by CommonClimate** [fzhu2e/cfr#10]
Right now, a `RuntimeWarning: divide by zero encountered in divide` is returned, but that corrupts the results; the method should instead remove records from the db if they don't have any overlap over the reference period.

**Comment by fzhu2e** [comment]
Reconstructed the code a bit regarding standardize() and center() for both ProxyRecord and ProxyDatabase in commit 6fe18c.
