### ISSUE TITLE
name 'PyVSL' is not defined

### ISSUE THREAD

**Issue by KINDREDFFF** [fzhu2e/cfr#16]
when I run the step:
`mdl.calibrate() `
it cames some problem
`name 'PyVSL' is not defined`
I try to insatll PyVSL,but it seems not work

**Comment by fzhu2e** [comment]
Hi, in the installation guide, it's mentioned that the below command is required in order to enable the PSMs:
```
pip install "cfr[psm]"
```

You may also just
```
pip install pyvsl
```
to install PyVSL. If you have tried this but failed, what message did you get?

**Comment by KINDREDFFF** [comment]
![image](https://github.com/fzhu2e/cfr/assets/106014676/a5ab8054-376b-49a8-b00d-32fbcea197be)

**Comment by KINDREDFFF** [comment]
as you see,I have installed the PyVSL,I can import it.
I run the `pip install "cfr[psm]"`and` pip install pyvsl`
but it still not works

**Comment by fzhu2e** [comment]
Can you check if `pathos`, `statsmodels`, and `fbm` have been installed as well?

**Comment by KINDREDFFF** [comment]
![image](https://github.com/fzhu2e/cfr/assets/106014676/fca38704-5166-49e9-bd2e-191b0f6c756f)
already installed

**Comment by KINDREDFFF** [comment]
![image](https://github.com/fzhu2e/cfr/assets/106014676/0f780b0d-68e9-4bff-bbf6-3539d7833e21)
already installed

**Comment by fzhu2e** [comment]
Which version of cfr are you using? In the latest version the `PyVSL` call should be at L1091 instead of L1073. To upgrade: `pip install -U cfr`.

**Comment by KINDREDFFF** [comment]
![image](https://github.com/fzhu2e/cfr/assets/106014676/ebe4d6bf-b622-43bc-ae01-92a32f2cfea3)

**Comment by fzhu2e** [comment]
OK. No essential difference then.

Can you run the below successfully?
```
    import statsmodels.formula.api as smf
    from pathos.multiprocessing import ProcessingPool as Pool
    import fbm
    import PyVSL
```

**Comment by KINDREDFFF** [comment]
![image](https://github.com/fzhu2e/cfr/assets/106014676/41496a9e-16fe-4354-820e-558ae0799df0)
yes

**Comment by fzhu2e** [comment]
I just did a test with v2024.1.26 and it works fine.

Can you restart your Jupyter kernel and try again?

If the source code: https://github.com/fzhu2e/cfr/blob/main/cfr/psm.py#L9-L12 can be loaded without any issue, it shouldn't prompt `name 'PyVSL' is not defined`.

**Comment by KINDREDFFF** [comment]
ok,thaks.i restart it,and the error is changed
![image](https://github.com/fzhu2e/cfr/assets/106014676/9c60183d-8257-4750-ac78-daa8fa9c1a5e)

**Comment by fzhu2e** [comment]
`octave` should be installed, see the annotation

**Comment by KINDREDFFF** [comment]
![image](https://github.com/fzhu2e/cfr/assets/106014676/c288ae1a-ace2-44d9-8af4-a696c985e249)

**Comment by KINDREDFFF** [comment]
ok,thank you so much.I gonna update CFR and try it again.
