### ISSUE TITLE
the nc_file must have one var and its name must be tar or pr?how can i use the rename_dic

### ISSUE THREAD

**Issue by KINDREDFFF** [fzhu2e/cfr#17]
![image](https://github.com/fzhu2e/cfr/assets/106014676/e6c8e2e8-b47c-483b-93d5-3920cb43a9bd)

**Comment by fzhu2e** [comment]
Yes. In `path_dict`, it should be `tas` and `pr`.
In `rename_dict`, it should be like:
```
rename_dict = {
    `tas`: `tmp`,
    `pr`: `pre`,
}
```

**Comment by KINDREDFFF** [comment]
![image](https://github.com/fzhu2e/cfr/assets/106014676/0381cc98-91d4-4959-af62-d468626c253d)
![image](https://github.com/fzhu2e/cfr/assets/106014676/aabdc569-7c0e-499b-b5b0-e2b9fdd04450)

**Comment by fzhu2e** [comment]
In path_dict, it should be `tas` and `pr`, instead of the original variable names.
`tas` and `pr` have special meanings in `cfr`.

**Comment by KINDREDFFF** [comment]
emm...how can I solve it

**Comment by fzhu2e** [comment]
```
path_dict = {
    'tas': ...,
    'pr': ...,
}
```
