### ISSUE TITLE
Strong assumptions made in `ProxyDatabase.to_ds()`

### ISSUE THREAD

**Issue by CommonClimate** [fzhu2e/cfr#23]
In exporting my database (shown here) to netCDF, `cfr` eliminates a full 50 records (from 652 to 602) without explaining why. Looking under the hood, I see that this must happen in `to_ds()`
[PAGES2k_Iso2k_CoralHydro2k_db.pdf](https://github.com/user-attachments/files/17528037/PAGES2k_Iso2k_CoralHydro2k_db.pdf)

That code removes everything before 1 CE, which makes quite a lot of assumptions about user's goals... Maybe this could a customizable parameter? However it does not explain why 50 records go up in smokes. I have scanned for duplicates extensively already, but even if the code did this internally, it needs to notify the user for traceability.  Where in the code is that happening, and how can I make this more flexible/transparent?
![Screenshot 2024-10-25 at 15 42 39](https://github.com/user-attachments/assets/b3a523ce-9bcb-491b-8bc7-f5a79176fb70)

**Comment by fzhu2e** [comment]
When the proxy contains time axis before 1CE, there will be error when saving to netcdf.
`to_ds()` has a verbose argument to print out warnings
```
        if verbose:
            utils.p_warning(f'>>> Data before 1 CE is dropped for records: {pid_truncated}.')
```
which I should have put into the call in `to_nc()` as well.
```
  ds = self.to_ds(annualize=annualize, months=months, **verbose=verbose**)
```

This is an example that there are quite a few experimental features in cfr that I didn't have time to make everything perfect. Perhaps I should have removed them. Sorry for the confusion.

**Comment by CommonClimate** [comment]
Thanks! Re: the 50 proxy series that disappeared (652 to 602), it looks like the issue is in `from_df()`, so I'll close this one
